name = "d-directory"
main = "server/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

#[assets]
#directory = "./dist"
#binding = "ASSETS"

[env.production]
name = "d-directory-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "d-directory-db"
database_id = "${DATABASE_ID}"

[env.production.durable_objects]
bindings = [
	{ name = "BACKEND", class_name = "Backend" }
]

[[env.production.containers]]
class_name = "Backend"
image = "./Dockerfile"

[[env.production.migrations]]
new_sqlite_classes = ["Backend"]
tag = "v1"

[env.production.vars]
NODE_ENV = "production"

[env.production.observability]
enabled = true

# Environment variables for production
# These will be set in Cloudflare dashboard:
# SESSION_SECRET = "your-session-secret"
# CLOUDFLARE_API_TOKEN = "your-api-token"