name = "d-directory"
main = "server/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

#[assets]
#directory = "./dist"
#binding = "ASSETS"

[[containers]]
class_name = "Backend"
image = "./Dockerfile"

[[durable_objects.bindings]]
class_name = "Backend"
name = "BACKEND"

[env.production]
name = "d-directory-prod"

[[d2_databases]]
binding = "DB"
database_name = "d-directory-db"
database_id = "${DATABASE_ID}"

[[migrations]]
new_sqlite_classes = [ "Backend" ]
tag = "v1"

[vars]
NODE_ENV = "production"

# Environment variables for production
# These will be set in Cloudflare dashboard:
# SESSION_SECRET = "your-session-secret"
# CLOUDFLARE_API_TOKEN = "your-api-token"